development:
  adapter: postgresql
  host: localhost
  username: tmahoney
  database: erinmahoneyphoto_dev

test:
  adapter: postgresql
  host: localhost
  username: tmahoney
  database: erinmahoneyphoto_test

#production:
  #adapter: postgresql
  #host: localhost
  #username: tmahoney
  #database: erinmahoneyphoto_prod
