Series.create(name: "jacket", display_name: "The Jacket", index: 0, image_count: 18)
Series.create(name: "another", display_name: "Another Me", index: 1, image_count: 12)
Series.create(name: "thesis", display_name: "Thesis", index: 2, image_count: 10)
Series.create(name: "tourist", display_name: "Tourist", index: 3, image_count: 20)
Series.create(name: "thumbelina", display_name: "Thumbelina", index: 4, image_count: 10)
Series.create(name: "isolation", display_name: "Isolation", index: 5, image_count: 12)
Series.create(name: "weather", display_name: "Strange Weather", index: 6, image_count: 3)
